import { apiService, toFormData } from '../apiService';

/**
 * Workflows API Service
 * Handles workflow management via /api/workflows endpoints.
 *
 * Backend model fields:
 *   uuid, name, notes, type (campaign|widget|report|alert|route|event),
 *   type_uuid, enabled, strategy (sequential|parallel), profile (hstore),
 *   meta (hstore), actions (hstore), customer_uuid, segment_uuids[],
 *   environment_uuids[], triggers[], created_at, updated_at
 *
 * Visual editor data (nodes/edges) is stored as JSON strings inside
 * the profile hstore: profile[nodes], profile[edges], profile[settings].
 */
export const workflowsApi = {
  /**
   * List workflows with search/filter/pagination
   * @param {Object} params - Query parameters (page, per_page, search, order_by, etc.)
   * @returns {Promise<Object>} - { data: [...], total: N }
   */
  getWorkflows: async (params = {}) => {
    const queryParts = [];
    for (const [key, value] of Object.entries(params)) {
      if (value !== undefined && value !== null && value !== '') {
        if (typeof value === 'object' && !Array.isArray(value)) {
          // Nested search params: search[name]=foo
          for (const [sk, sv] of Object.entries(value)) {
            if (sv !== undefined && sv !== null && sv !== '') {
              queryParts.push(`search[${sk}]=${encodeURIComponent(sv)}`);
            }
          }
        } else {
          queryParts.push(`${key}=${encodeURIComponent(value)}`);
        }
      }
    }
    const queryString = queryParts.join('&');
    const url = `/api/workflows${queryString ? `?${queryString}` : ''}`;
    return apiService.get(url, {}, 'fetching workflows', false);
  },

  /**
   * Get a single workflow by UUID
   * @param {string} id - Workflow UUID
   * @returns {Promise<Object>} - Workflow object
   */
  getWorkflow: async (id) => {
    const url = `/api/workflows/${id}`;
    return apiService.get(url, {}, `fetching workflow ${id}`, false);
  },

  /**
   * Create a new workflow
   * @param {Object} data - Workflow data
   * @param {string} data.name - Workflow name
   * @param {string} [data.type] - Workflow type (campaign|widget|report|alert|route|event)
   * @param {boolean} [data.enabled] - Whether workflow is active
   * @param {string} [data.notes] - Description/notes
   * @param {string} [data.strategy] - Execution strategy (sequential|parallel)
   * @param {Array} [data.nodes] - ReactFlow nodes (will be stored as JSON in profile)
   * @param {Array} [data.edges] - ReactFlow edges (will be stored as JSON in profile)
   * @param {Object} [data.settings] - Flow settings (will be stored as JSON in profile)
   * @returns {Promise<Object>} - Created workflow
   */
  createWorkflow: async (data) => {
    const url = '/api/workflows';
    const headers = { 'Content-Type': 'application/x-www-form-urlencoded' };
    const payload = {
      name: data.name,
      type: data.type || 'campaign',
      enabled: data.enabled !== false ? 'true' : 'false',
    };
    // type_uuid is auto-generated by the database — do not send
    if (data.service_uuid) payload.service_uuid = data.service_uuid;
    if (data.notes) payload.notes = data.notes;
    if (data.strategy) payload.strategy = data.strategy;
    if (data.environment_uuid) payload.environment_uuid = data.environment_uuid;
    // Pack nodes/edges/settings into flow_data JSONB
    payload.flow_data = JSON.stringify({
      nodes: data.nodes || [],
      edges: data.edges || [],
      settings: data.settings || {},
    });
    const formData = toFormData(payload);
    return apiService.post(url, formData, headers, 'creating workflow', true);
  },

  /**
   * Update an existing workflow
   * @param {string} id - Workflow UUID
   * @param {Object} data - Fields to update
   * @returns {Promise<Object>} - Updated workflow
   */
  updateWorkflow: async (id, data) => {
    const url = `/api/workflows/${id}`;
    const headers = { 'Content-Type': 'application/x-www-form-urlencoded' };
    const payload = {};
    if (data.name !== undefined) payload.name = data.name;
    if (data.type !== undefined) payload.type = data.type;
    if (data.enabled !== undefined) payload.enabled = String(data.enabled);
    if (data.notes !== undefined) payload.notes = data.notes;
    if (data.strategy !== undefined) payload.strategy = data.strategy;
    if (data.service_uuid !== undefined) payload.service_uuid = data.service_uuid;
    // Pack flow_data — support direct object or legacy nodes/edges/settings
    if (data.flow_data !== undefined) {
      payload.flow_data = typeof data.flow_data === 'string'
        ? data.flow_data
        : JSON.stringify(data.flow_data);
    } else if (data.nodes || data.edges || data.settings) {
      payload.flow_data = JSON.stringify({
        nodes: data.nodes || [],
        edges: data.edges || [],
        settings: data.settings || {},
      });
    }
    const formData = toFormData(payload);
    return apiService.patch(url, formData, headers, `updating workflow ${id}`, true);
  },

  /**
   * Test a workflow by simulating an event
   * @param {string} uuid - Workflow UUID
   * @param {Object} eventData - Test event data
   * @param {string} [eventData.event_name] - Event type (e.g. 'user.answer')
   * @param {string} [eventData.caller_id_number] - Caller ID
   * @param {string} [eventData.extension_username] - Extension
   * @param {string} [eventData.direction] - Call direction
   * @param {string} [eventData.duration_time] - Duration
   * @param {string} [eventData.did_number] - DID number
   * @param {string} [eventData.queue_name] - Queue name
   * @returns {Promise<Object>} - Test result with webhook_result
   */
  testWorkflow: async (uuid, eventData = {}) => {
    const url = `/api/workflows/${uuid}/test`;
    const headers = { 'Content-Type': 'application/x-www-form-urlencoded' };
    const formData = toFormData(eventData);
    return apiService.post(url, formData, headers, `testing workflow ${uuid}`, false);
  },

  /**
   * Get the generated Ruby/YAML code for a workflow's flow
   * Uses existing GET /workflows/:id/flow?format=ruby|yaml|json
   * @param {string} uuid - Workflow UUID
   * @param {string} [format='ruby'] - Output format (ruby|yaml|json)
   * @returns {Promise<string>} - Generated code as text
   */
  getFlowCode: async (uuid, format = 'ruby') => {
    const url = `/api/workflows/${uuid}/flow?format=${format}`;
    return apiService.get(url, {}, `fetching flow code for ${uuid}`, false);
  },

  /**
   * Fetch registered PocketFlow node types with self-describing schemas
   * @returns {Promise<Object>} - Map of type → { label, description, category, fields, outputs }
   */
  getNodeTypes: async () => {
    return apiService.get('/api/workflows/node_types', {}, 'fetching node types', false);
  },

  /**
   * Delete a workflow
   * @param {string} id - Workflow UUID
   * @returns {Promise<Object>} - Deletion confirmation
   */
  deleteWorkflow: async (id) => {
    const url = `/api/workflows/${id}`;
    return apiService.delete(url, {}, `deleting workflow ${id}`, true);
  },

};

export default workflowsApi;
