defmodule ConnectixWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :connectix

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_connectix_key",
    signing_salt: "U+UHBugB",
    same_site: "Lax"
  ]

  # `/ws/events` — the browser realtime feed. A raw WebSock upgrade rather than
  # a Phoenix socket: the contract is a flat JSON frame protocol that shipped
  # clients already speak (see voipappz/chrome/docs/REALTIME_CONTRACT.md), and
  # Phoenix's own socket would wrap every message in a join/ref envelope.
  #
  # Placed BEFORE Plug.Static so the catch-all cannot answer the upgrade.
  plug :realtime_events

  defp realtime_events(%Plug.Conn{request_path: "/ws/events"} = conn, _opts) do
    ConnectixWeb.RealtimeSocket.upgrade(Plug.Conn.fetch_query_params(conn))
  end

  defp realtime_events(conn, _opts), do: conn

  # The LiveView socket, for LiveDashboard and the agent debugger under `/dev`.
  # There is no LiveView UI any more — the React portal is the UI — so outside
  # dev nothing is listening on this and it should not accept upgrades.
  if Application.compile_env(:connectix, :dev_routes, false) do
    socket "/live", Phoenix.LiveView.Socket,
      websocket: [connect_info: [session: @session_options]],
      longpoll: [connect_info: [session: @session_options]]
  end

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :connectix,
    gzip: not code_reloading?,
    only: ConnectixWeb.static_paths()

  if Code.ensure_loaded?(Tidewave) do
    plug Tidewave
  end

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # Ahead of Plug.Parsers on purpose. Meta signs the *raw* request body, and
  # the parser consumes it — after it runs, `read_body/1` returns "" and the
  # signature can never match. `Anu.Webhook.Plug` treats a failed check as a
  # silent 200, so a webhook mounted in the router instead of here would look
  # healthy to Meta while dropping every message.
  plug :whatsapp_webhook

  # Forwarding must happen BEFORE the parsers: they consume the request body,
  # and a proxy that re-reads it afterwards sends an empty one — which the
  # upstream answers with a puzzled 4xx rather than an error that names the
  # cause. Also before the router, which raises on an unmatched path instead of
  # falling through. Inert without ENGINE_URL.
  plug ConnectixWeb.Plugs.EngineProxy

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  # The Vite/React dashboard, served from this app. After the proxy and the
  # router so real routes win, and inert unless SPA_ROOT is set.
  plug ConnectixWeb.Plugs.Spa

  plug ConnectixWeb.Router

  @whatsapp_webhook_opts Anu.Webhook.Plug.init(handler: Connectix.Channels.WhatsApp.Handler)

  defp whatsapp_webhook(%Plug.Conn{path_info: ["webhooks", "whatsapp"]} = conn, _opts),
    do: Anu.Webhook.Plug.call(conn, @whatsapp_webhook_opts)

  defp whatsapp_webhook(conn, _opts), do: conn
end
