defmodule ConnectixWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :connectix

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_connectix_key",
    signing_salt: "U+UHBugB",
    same_site: "Lax"
  ]

  # `/ws/events` — the browser realtime feed. A raw WebSock upgrade rather than
  # a Phoenix socket: the contract is a flat JSON frame protocol that shipped
  # clients already speak (see voipappz/chrome/docs/REALTIME_CONTRACT.md), and
  # Phoenix's own socket would wrap every message in a join/ref envelope.
  #
  # Placed BEFORE Plug.Static so the catch-all cannot answer the upgrade.
  plug :realtime_events

  defp realtime_events(%Plug.Conn{request_path: "/ws/events"} = conn, _opts) do
    ConnectixWeb.RealtimeSocket.upgrade(Plug.Conn.fetch_query_params(conn))
  end

  defp realtime_events(conn, _opts), do: conn

  # `/voice/ws` — the Feline voice pipeline (`Connectix.Voice.FelinePipeline`,
  # `Connectix.Voice.SagentsBridge`). Gated by the SAME `Plugs.BasicAuth` the
  # `:browser` pipeline uses for the LiveView UI: a browser that has already
  # authenticated to load `/chat` has the credential cached and sends it
  # automatically on this handshake too (it's still an HTTP request before the
  # Upgrade), so no separate token scheme — this app has exactly one identity
  # already, `ConnectixWeb.UserAuth.resolve_scope/0`.
  #
  # `conversation_id` comes from the query string so a voice call can attach
  # to the SAME conversation a chat session already has open — the turn goes
  # through `Connectix.Turns` like any other origin, so it lands in the same
  # transcript `ChatLive` is already streaming. Absent, a fresh voice
  # conversation is created.
  #
  # Placed BEFORE Plug.Static for the same reason as `/ws/events`: a catch-all
  # must not be able to answer the upgrade.
  plug :voice_ws

  defp voice_ws(%Plug.Conn{request_path: "/voice/ws"} = conn, _opts) do
    conn = Plug.Conn.fetch_query_params(conn)
    conn = ConnectixWeb.Plugs.BasicAuth.call(conn, [])

    if conn.halted do
      conn
    else
      scope = ConnectixWeb.UserAuth.resolve_scope()

      case resolve_voice_conversation(scope, conn.query_params["conversation_id"]) do
        {:ok, conversation_id} ->
          conn
          |> WebSockAdapter.upgrade(
            Feline.Transports.WebSocket.Handler,
            %{bot: Connectix.Voice.FelinePipeline.bot(scope, conversation_id)},
            []
          )
          |> Plug.Conn.halt()

        {:error, reason} ->
          conn
          |> Plug.Conn.send_resp(422, "voice conversation unavailable: #{inspect(reason)}")
          |> Plug.Conn.halt()
      end
    end
  end

  defp voice_ws(conn, _opts), do: conn

  defp resolve_voice_conversation(_scope, id) when is_binary(id) and id != "", do: {:ok, id}

  defp resolve_voice_conversation(scope, _absent) do
    case Connectix.Conversations.create_conversation(scope, %{source: "voice", title: "Voice call"}) do
      {:ok, conversation} -> {:ok, conversation.id}
      error -> error
    end
  end

  # The LiveView socket — the agent-chat UI (`/`, `/chat`, see
  # `ConnectixWeb.Router`) always, plus LiveDashboard/the agent debugger
  # under `/dev` when `:dev_routes` is on. `ConnectixWeb.Plugs.BasicAuth`
  # gates the HTTP mount that hands out the page; nothing separately gates
  # this socket, matching the router's own reasoning for why the LiveView
  # routes are unconditional now.
  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :connectix,
    gzip: not code_reloading?,
    only: ConnectixWeb.static_paths()

  # THE IONIC APP, bundled into this release and served from this origin.
  #
  # `from: {:connectix, "priv/app"}` and NOT `priv/static/app`: `mix
  # phx.digest` walks all of `priv/static` whatever `static_paths/0` says, so a
  # bundle there gets a second content-hashed copy of every Angular chunk and a
  # `cache_manifest.json` entry — for nothing, since Angular hashes its own
  # filenames already. Outside `priv/static` the question does not arise. Same
  # reasoning as the extension zip in `priv/extension`.
  #
  # `gzip: true` serves `foo.js.gz` IF IT EXISTS, and it is `phx.digest` that
  # normally writes those. Bypassing digest means the `.gz` files are made by
  # the build instead — `make -C ionic compress`, and the `ionic` stage of
  # Dockerfile.production. Without that step this option silently does nothing
  # and every phone downloads the uncompressed bundle.
  #
  # UNGATED, like the extension's routes and for the same reason: this app
  # authenticates with a token from `POST /auth/user_login`, and
  # `Plugs.BasicAuth` in front of it would prompt for a second, unrelated
  # credential that no mobile build can supply. `/app` itself and any path
  # under it that is not a file fall through to `ConnectixWeb.AppController`.
  plug Plug.Static,
    at: "/app",
    from: {:connectix, "priv/app"},
    gzip: not code_reloading?

  if Code.ensure_loaded?(Tidewave) do
    plug Tidewave
  end

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # Ahead of Plug.Parsers on purpose. Meta signs the *raw* request body, and
  # the parser consumes it — after it runs, `read_body/1` returns "" and the
  # signature can never match. `Anu.Webhook.Plug` treats a failed check as a
  # silent 200, so a webhook mounted in the router instead of here would look
  # healthy to Meta while dropping every message.
  plug :whatsapp_webhook

  # Forwarding must happen BEFORE the parsers: they consume the request body,
  # and a proxy that re-reads it afterwards sends an empty one — which the
  # upstream answers with a puzzled 4xx rather than an error that names the
  # cause. Also before the router, which raises on an unmatched path instead of
  # falling through. Inert without ENGINE_URL.
  plug ConnectixWeb.Plugs.EngineProxy

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  # NOTHING SERVES A BUNDLE HERE. The LiveView UI (WelcomeLive at "/", ChatLive
  # at "/chat") is the UI. A React SPA plug used to sit at this point in the
  # pipeline and was unmounted when LiveView took the origin; the module is now
  # deleted rather than kept "in case", because a plug nothing mounts is a plug
  # nobody maintains, and this one would shadow both routes the moment someone
  # put it back — it answered "/" and every extensionless path unconditionally.

  plug ConnectixWeb.Router

  @whatsapp_webhook_opts Anu.Webhook.Plug.init(handler: Connectix.Channels.WhatsApp.Handler)

  defp whatsapp_webhook(%Plug.Conn{path_info: ["webhooks", "whatsapp"]} = conn, _opts),
    do: Anu.Webhook.Plug.call(conn, @whatsapp_webhook_opts)

  defp whatsapp_webhook(conn, _opts), do: conn
end
